name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true # Ensures the latest version that matches the version spec is used

      - name: Install dependencies
        run: npm install

      - name: Archive the project
        run: zip -r my-app.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          pip install awsebcli
          eb init -p node.js ${{ secrets.EB_APPLICATION_NAME }} --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          eb deploy --staged --label github-actions-deploy
